/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FeedColumn: typeof import('./src/components/Feed/FeedColumn.vue')['default']
    FeedPost: typeof import('./src/components/Feed/FeedPost.vue')['default']
    'IMdi:newspaperVariantMultiple': typeof import('~icons/mdi/newspaper-variant-multiple')['default']
    'IMdi:paintOutline': typeof import('~icons/mdi/paint-outline')['default']
    'IMdi:playlistAdd': typeof import('~icons/mdi/playlist-add')['default']
    IMdiRobotAngry: typeof import('~icons/mdi/robot-angry')['default']
    'IMingcute:butterfly2Line': typeof import('~icons/mingcute/butterfly2-line')['default']
    'IMingcute:group3Fill': typeof import('~icons/mingcute/group3-fill')['default']
    'IMingcute:heartFill': typeof import('~icons/mingcute/heart-fill')['default']
    'IMingcute:home4Line': typeof import('~icons/mingcute/home4-line')['default']
    'IMingcute:menuLine': typeof import('~icons/mingcute/menu-line')['default']
    'IMingcute:refresh3Fill': typeof import('~icons/mingcute/refresh3-fill')['default']
    'IMingcute:repeatLine': typeof import('~icons/mingcute/repeat-line')['default']
    'IMingcute:settings2Line': typeof import('~icons/mingcute/settings2-line')['default']
    'IMingcute:user1Line': typeof import('~icons/mingcute/user1-line')['default']
    'ISolar:chatDotsOutline': typeof import('~icons/solar/chat-dots-outline')['default']
    PostDetailIcon: typeof import('./src/components/Post/PostDetailIcon.vue')['default']
    PostDetailModal: typeof import('./src/components/Post/PostDetailModal.vue')['default']
    PostOptionsMenu: typeof import('./src/components/Post/PostOptionsMenu.vue')['default']
    PostOptionsMenuItem: typeof import('./src/components/Post/PostOptionsMenuItem.vue')['default']
    PostReply: typeof import('./src/components/Post/PostReply.vue')['default']
    SidebarButtonNormal: typeof import('./src/components/Navbar/SidebarButtonNormal.vue')['default']
    UnreadMsgCount: typeof import('./src/components/Decorations/UnreadMsgCount.vue')['default']
    UserButton: typeof import('./src/components/Navbar/UserButton.vue')['default']
  }
}
