/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors:{
        // primary: s"var(--color-primary-text) / <alpha-value>",
        blueskyBlue: "oklch(from var(--color-bluesky-blue) l c h / <alpha-value>)",
        deleteBtnBG: "oklch(from var(--color-delete-btn-bg) l c h / <alpha-value>)",
        deleteBtnBGHover: "oklch(from var(--color-delete-btn-bg-hover) l c h / <alpha-value>)",
        deleteBtnBGActive: "oklch(from var(--color-delete-btn-bg-active) l c h / <alpha-value>)",
        primary: "oklch(from var(--color-primary-text) l c h / <alpha-value>)",
        primaryInverted: "oklch(from var(--color-primary-text-inverted) l c h / <alpha-value>)",
        secondary: "oklch(from var(--color-secondary-text) l c h / <alpha-value>)",
        secondaryHover: "oklch(from var(--color-secondary-text-hover) l c h / <alpha-value>)",
        hover: "oklch(from var(--color-hover) l c h / <alpha-value>)",
        btn: "oklch(from var(--color-btn) l c h / <alpha-value>)",
        btnSubtle: "oklch(from var(--color-btn-subtle) l c h / <alpha-value>)",
        btnText: "oklch(from var(--color-btn-text) l c h / <alpha-value>)",
        btnHover: "oklch(from var(--color-btn-hover) l c h / <alpha-value>)",
        sidebar: "oklch(from var(--color-sidebar) l c h / <alpha-value>)",
        feedBtn: "oklch(from var(--color-feed-btn) l c h / <alpha-value>)",
        feedTypeBtnHover: "oklch(from var(--color-feedtype-btn-hover) l c h / <alpha-value>)",
        feedColumnBG: "oklch(from var(--color-fc-bg) l c h / <alpha-value>)",
        postBG: "oklch(from var(--color-post-bg) l c h / <alpha-value>)",
        postMsg: "oklch(from var(--color-post-msg) l c h / <alpha-value>)",
        postFocusBG: "oklch(from var(--color-post-focus-bg) l c h / <alpha-value>)",
        outline: "oklch(from var(--color-border) l c h / <alpha-value>)",
        outlineLighter: "oklch(from var(--color-border-lighter) l c h / <alpha-value>)",
        banner: "oklch(from var(--color-banner) l c h / <alpha-value>)",
        focusBG: "oklch(from var(--color-user-focus-bg) l c h / <alpha-value>)",
        disabled: "oklch(from var(--color-disabled) l c h / <alpha-value>)",
        disabledBG: "oklch(from var(--color-disabled-bg) l c h / <alpha-value>)",
        toggleButton: "oklch(from var(--color-toggle-button) l c h / <alpha-value>)",
        toggleGutter: "oklch(from var(--color-toggle-gutter) l c h / <alpha-value>)",
        checkboxHover: "oklch(from var(--color-checkbox-hover) l c h / <alpha-value>)",
        feedHighlight: "oklch(from var(--color-feed-highlight) l c h / <alpha-value>)",
        viewportBG: "oklch(from var(--color-viewport-background) l c h / <alpha-value>)",
        messageDismiss: "oklch(from var(--color-message-dismiss) l c h / <alpha-value>)",
        loginHighlight: "oklch(from var(--color-login-highlight) l c h / <alpha-value>)",
        searchbarBtn: "oklch(from var(--color-searchbar-btn) l c h / <alpha-value>)",
        searchbarBtnHover: "oklch(from var(--color-searchbar-btn-hover) l c h / <alpha-value>)",
        searchbarBG: "oklch(from var(--color-searchbar-bg) l c h / <alpha-value>)",
        searchbarBorder: "oklch(from var(--color-searchbar-border) l c h / <alpha-value>)",
        searchbarBorderDisabled: "oklch(from var(--color-searchbar-border-disabled) l c h / <alpha-value>)",
        searchbarFocusHightlight: "oklch(from var(--color-searchbar-focus-highlight) l c h / <alpha-value>)",
        searchbarResultHover: "oklch(from var(--color-searchbar-result-hover) l c h / <alpha-value>)",
        searchbarHandle: "oklch(from var(--color-searchbar-handle) l c h / <alpha-value>)",
        loginBtn: "oklch(from var(--color-login-btn) l c h / <alpha-value>)",
        loginBtnHover: "oklch(from var(--color-login-btn-hover) l c h / <alpha-value>)",
        loginHostHover: "oklch(from var(--color-login-host-hover) l c h / <alpha-value>)",
        feedtypeBtnSelected: "oklch(from var(--color-feedtype-btn-selected) l c h / <alpha-value>)",
        feedtypeBtnFocusHighlight: "oklch(from var(--color-feedtype-btn-focus-highlight) l c h / <alpha-value>)",
        savemodalBG: "oklch(from var(--color-savemodal-bg) l c h / <alpha-value>)",
        savemodalFileExtBG: "oklch(from var(--color-savemodal-ext-bg) l c h / <alpha-value>)",
        embedHoverBG: "oklch(from var(--color-embed-hover-bg) l c h / <alpha-value>)",
        embedHoverBorder: "oklch(from var(--color-embed-hover-border) l c h / <alpha-value>)",
        scrollbarTrack: "oklch(from var(--color-scrollbar-track) l c h / <alpha-value>)",
        scrollbarThumb: "oklch(from var(--color-scrollbar-thumb) l c h / <alpha-value>)",
        scrollbarThumbHover: "oklch(from var(--color-scrollbar-thumb-hover) l c h / <alpha-value>)",
        navbarBtn: "oklch(from var(--color-navbar-btn) l c h / <alpha-value>)",
        navbarBtnHover: "oklch(from var(--color-navbar-btn-hover) l c h / <alpha-value>)",
        navbarBtnText: "oklch(from var(--color-navbar-btn-text) l c h / <alpha-value>)",
        feedColumnSettingsBG: "oklch(from var(--color-feedcolumn-settings-bg) l c h / <alpha-value>)",
        feedColumnSettingsBtnHover: "oklch(from var(--color-feedcolumn-settings-btn-hover) l c h / <alpha-value>)",
        feedColumnSettingsBtnSelected: "oklch(from var(--color-feedcolumn-settings-btn-selected) l c h / <alpha-value>)",
        feedColumnSettingsBtnSelectedHover: "oklch(from var(--color-feedcolumn-settings-btn-selected-hover) l c h / <alpha-value>)",
        userFocusModalBannerBG: "oklch(from var(--color-userfocusmodal-banner-bg) l c h / <alpha-value>)",
        postFocusModalDetailsShadow: "oklch(from var(--color-postfocusmodal-details-shadow) l c h / <alpha-value>)",
        logoFill: "oklch(from var(--color-logo-fill) l c h / <alpha-value>)",
        aboutPageBanner: "oklch(from var(--color-about-page-banner) l c h / <alpha-value>)",
        aboutPageBannerBtnHover: "oklch(from var(--color-about-page-banner-btn-hover) l c h / <alpha-value>)",
        spoilerBlackoutColor: "oklch(from var(--color-spoiler-blackout-color) l c h / <alpha-value>)",
        radioButtonSelected: "oklch(from var(--color-radio-button-selected) l c h / <alpha-value>)",
        donationButtonBG: "oklch(from var(--color-donation-btn-bg) l c h / <alpha-value>)",
        donationButtonIconHover: "oklch(from var(--color-donation-btn-icon-hover) l c h / <alpha-value>)",
        modernToggleBtnToggleFill: "oklch(from var(--color-modern-toggle-btn-toggle-fill) l c h / <alpha-value>)",
        modernToggleBtnBorder: "oklch(from var(--color-modern-toggle-btn-border) l c h / <alpha-value>)",
        modernToggleBtnBorderHover: "oklch(from var(--color-modern-toggle-btn-border-hover) l c h / <alpha-value>)",
        modernToggleBtnBG: "oklch(from var(--color-modern-toggle-btn-bg) l c h / <alpha-value>)",
        modernToggleBtnBGSelected: "oklch(from var(--color-modern-toggle-btn-bg-selected) l c h / <alpha-value>)",
        checkedButtonBG: "oklch(from var(--color-checked-btn-bg) l c h / <alpha-value>)",
        checkedButtonBGHover: "oklch(from var(--color-checked-btn-bg-hover) l c h / <alpha-value>)",
        checkedButtonBGSelected: "oklch(from var(--color-checked-btn-bg-selected) l c h / <alpha-value>)",
        checkedButtonCheckmark: "oklch(from var(--color-checked-btn-checkmark) l c h / <alpha-value>)",
        customFeedBtnBGHover: "oklch(from var(--color-custom-feed-btn-bg-hover) l c h / <alpha-value>)",
        customFeedBtnBGActive: "oklch(from var(--color-custom-feed-btn-bg-active) l c h / <alpha-value>)",
        itemTagBG: "oklch(from var(--color-item-tag-bg) l c h / <alpha-value>)",
        itemTagBGActive: "oklch(from var(--color-item-tag-bg-active) l c h / <alpha-value>)",
        itemTagBorder: "oklch(from var(--color-item-tag-border) l c h / <alpha-value>)",
        placeholderPulseBG: "oklch(from var(--color-placeholder-pulse-bg) l c h / <alpha-value>)",
        feedNoticeBG: "oklch(from var(--color-feed-notice-bg) l c h / <alpha-value>)",
        submitBtnBG: "oklch(from var(--color-submit-btn-bg) l c h / <alpha-value>)",
        submitBtnBGHover: "oklch(from var(--color-submit-btn-bg-hover) l c h / <alpha-value>)",
        submitBtnBGActive: "oklch(from var(--color-submit-btn-bg-active) l c h / <alpha-value>)",
        accountMuteLabelBG: "oklch(from var(--color-account-mute-label-bg) l c h / <alpha-value>)",
        postBookmark: "oklch(from var(--color-post-bookmark) l c h / <alpha-value>)",
        postBookmarkHover: "oklch(from var(--color-post-bookmark-hover) l c h / <alpha-value>)",
        postBookmarkActive: "oklch(from var(--color-post-bookmark-active) l c h / <alpha-value>)",
      },
      fontSize:{
        feedPostName: '0.75rem',
        feedTimestamp: '0.5rem', // 8px
      },
      dropShadow:{
        'md-harder': '0 4px 4px rgba(0, 0, 0, 0.75)'
      },
      boxShadow:{
        'scroll-underline' : '0 6px 4px -4px rgba(0,0,15,0.25)', //shadow-[rgba(0,0,15,0.25)_0px_6px_4px_-4px]
      }
    },
  },
  plugins: [],
  future:{
    hoverOnlyWhenSupported: true,
  }
}

