# name: CD Pipeline to DigitalOcean Droplet (staging and production)
# on:
#   push:
#     branches:
#       - dev
#   workflow_dispatch: {}
#   release:
#     types: published

# env:
#   PORT: 5001
#   IMAGE: ${{vars.IMAGE}}:${{github.sha}}
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     name: Setup, test, and build project
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Install dependencies
#         run: npm ci

#       - name: Test application
#         run: npm test
#   build:
#     needs: test
#     runs-on: ubuntu-latest
#     name: Setup project, SSH into droplet, and deploy
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

      # - name: Copy dist directory output to droplet via SSH and scp-action
      #   uses: appleboy/scp-action@v1
      #   with:
      #     host: ${{ secrets.DROPLET_HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: "/dist/*"
      #     target: ${{ secrets.DROPLET_BUILD_DESTINATION }}

      # - name: Copy dist directory output to droplet via SSH
      #   run: |
      #     mkdir lol
      #     END
      #   env:
      #     SSH_USER: ${{ secrets.USERNAME }}
      #     SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SSH_HOST: ${{ secrets.DROPLET_HOST }}